### ISSUE TITLE
Submit count data (CSV): Maximum upload size exceeded

### ISSUE THREAD

**Issue by ckeeling** [btmonier/iris#5]
Hello,

I have installed locally but when I select my count data file it gives the above error.  There are ~70,000 features and 190 samples = 32 MB csv file.  Maybe line 118 of irisServer.R should have a larger arbitrary max size?  It works if I shorten my file to under the current limit.
```
shiny.maxRequestSize = 30 * 1024^2,
```

**Comment by btmonier** [comment]
Hi Chris,

Thanks for the input. I have altered the `maxRequestSize` from 30 to 50. A pull request (#6)  has been submitted to merge the modifications to the master branch.
